/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import datos.ClienteService;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Michaell
 */
public class IFRBuscarModelo extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFRBuscarModelo
     */
    public IFRBuscarModelo() {
        initComponents();
        mostrarModelo();
        tabla.getTableHeader().setReorderingAllowed(false) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        txtagregar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Buscar Modelo");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        txtagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/agregar.png"))); // NOI18N
        txtagregar.setText("Agregar");
        txtagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtagregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        buscarModelo(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagregarActionPerformed
        int fila=tabla.getSelectedRow();
        int contador=0;
        if(fila>=0){
            
            String datos[]= new String[2];
        //String s;
            datos[0]=tabla.getValueAt(fila, 0).toString(); //id moedelo
            datos[1]=tabla.getValueAt(fila, 1).toString(); //mombre modelo
            //int stock = Integer.parseInt(tabla.getValueAt(fila, 2).toString());
            //arreglar problema
            
           //un dato                            3
           
          
     
                interfaces.IFRPedido2.modelo2.addRow(datos);
                //addComboCantidad(interfaces.IFRPedido2.tabla.getColumnModel().getColumn(2),interfaces.IFRPedido2.tabla);
                addComboColor(interfaces.IFRPedido2.tabla.getColumnModel().getColumn(3),interfaces.IFRPedido2.tabla);
                addComboTaco(interfaces.IFRPedido2.tabla.getColumnModel().getColumn(4),interfaces.IFRPedido2.tabla);
                addComboTalla(interfaces.IFRPedido2.tabla.getColumnModel().getColumn(5),interfaces.IFRPedido2.tabla);
                //interfaces.IFRProduccion.stockInsumo.add(stock);
            
           
           
        
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Seleccione una fila", 0);
        }
    }//GEN-LAST:event_txtagregarActionPerformed

    
    public void mostrarModelo() {
        DefaultTableModel modelo = ClienteService.mostrarModelo();
        tabla.setModel(modelo);
    }
    
    
     public void addComboColor(TableColumn columna,JTable tabla){
            //TableColumn tc =  tabla.getColumnModel().getColumn(columna);
            //tc.setCellEditor(tabla.getDefaultEditor(Boolean.class));
            //tc.setCellRenderer(tabla.getDefaultRenderer(Boolean.class));
            JComboBox c= new JComboBox();
            c.addItem("Azul");
            c.addItem("Negro");
            c.addItem("Blanco");
            columna.setCellEditor( new DefaultCellEditor(c));
            DefaultTableCellRenderer render = new DefaultTableCellRenderer();
            render.setToolTipText("seleccione");
            columna.setCellRenderer(render);
            
    }
     
          public void addComboTalla(TableColumn columna,JTable tabla){
            //TableColumn tc =  tabla.getColumnModel().getColumn(columna);
            //tc.setCellEditor(tabla.getDefaultEditor(Boolean.class));
            //tc.setCellRenderer(tabla.getDefaultRenderer(Boolean.class));
            JComboBox c= new JComboBox();
            c.addItem("36");
            c.addItem("37");
            c.addItem("38");
            c.addItem("39");
            c.addItem("40");
            c.addItem("42");
            c.addItem("43");
            columna.setCellEditor( new DefaultCellEditor(c));
            DefaultTableCellRenderer render = new DefaultTableCellRenderer();
            render.setToolTipText("seleccione");
            columna.setCellRenderer(render);
            
    }
          
      public void addComboCantidad(TableColumn columna,JTable tabla){
            //TableColumn tc =  tabla.getColumnModel().getColumn(columna);
            //tc.setCellEditor(tabla.getDefaultEditor(Boolean.class));
            //tc.setCellRenderer(tabla.getDefaultRenderer(Boolean.class));
            JTextField c= new JTextField();
            columna.setCellEditor( new DefaultCellEditor(c));
            DefaultTableCellRenderer render = new DefaultTableCellRenderer();
            render.setToolTipText("seleccione");
            columna.setCellRenderer(render);
            
    }
     
     public void addComboTaco(TableColumn columna,JTable tabla){
            //TableColumn tc =  tabla.getColumnModel().getColumn(columna);
            //tc.setCellEditor(tabla.getDefaultEditor(Boolean.class));
            //tc.setCellRenderer(tabla.getDefaultRenderer(Boolean.class));
            JComboBox c= new JComboBox();
            c.addItem("5");
            c.addItem("7");
            c.addItem("9");
            c.addItem("10");
            c.addItem("11");
         
            columna.setCellEditor( new DefaultCellEditor(c));
            DefaultTableCellRenderer render = new DefaultTableCellRenderer();
            render.setToolTipText("seleccione");
            columna.setCellRenderer(render);
            
    }
    
    
     public void buscarModelo(String buscar){
        DefaultTableModel modelo = ClienteService.buscarModelo(buscar);
        tabla.setModel(modelo);   
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton txtagregar;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
