/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.IUPrincipal.desktopPane;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Insumo;
import modelo.OrdenProduccion;
import modelo.Pedido;

/**
 *
 * @author Michaell
 */
public class IFRProduccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFRProduccion
     */
    public static ArrayList<Integer> stockInsumo= new ArrayList<Integer>();
    public static DefaultTableModel modelo2;
    public static int verificar;
    public static DefaultListModel modeloListaCortador;
    public static DefaultListModel modeloListaPerfilador;
    public static DefaultListModel modeloListaArmador;
    public static DefaultListModel modeloListaAlistador;
    public IFRProduccion() {
        initComponents();
        
       modelo2= new DefaultTableModel();
       modelo2.addColumn("id");
       modelo2.addColumn("Insumo");
       modelo2.addColumn("Cantidad");
       tabla.setModel(modelo2);
       tabla.getTableHeader().setReorderingAllowed(false) ;
      
       modeloListaAlistador= new DefaultListModel();
       modeloListaCortador= new DefaultListModel();
       modeloListaPerfilador= new DefaultListModel();
       modeloListaArmador= new DefaultListModel();
     
      limpiarLista(modeloListaAlistador, jalistador);
      limpiarLista(modeloListaCortador, jcortador);
      limpiarLista(modeloListaPerfilador, jperfilador);
      limpiarLista(modeloListaArmador, jarmador);
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidpedido = new javax.swing.JTextField();
        btnverpedido = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnverinsumo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btneliminarfilatabla = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jalistador = new javax.swing.JList<>();
        btnalistador = new javax.swing.JButton();
        btnquitaralistador = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jarmador = new javax.swing.JList<>();
        btnarmador = new javax.swing.JButton();
        btnquitararmador = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jperfilador = new javax.swing.JList<>();
        btnperfilador = new javax.swing.JButton();
        btnquitarperfilador = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jcortador = new javax.swing.JList<>();
        btnvercortador = new javax.swing.JButton();
        btnquitarcortador = new javax.swing.JButton();

        setClosable(true);
        setTitle("Produccion");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Pedido");

        txtidpedido.setEnabled(false);

        btnverpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnverpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverpedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtidpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnverpedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnverpedido)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtidpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnverinsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnverinsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverinsumoActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoger Insumo");

        btneliminarfilatabla.setText("Quitar");
        btneliminarfilatabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarfilatablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnverinsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btneliminarfilatabla, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnverinsumo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btneliminarfilatabla)
                .addContainerGap())
        );

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Lista Alistador");

        jScrollPane4.setViewportView(jalistador);

        btnalistador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnalistador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalistadorActionPerformed(evt);
            }
        });

        btnquitaralistador.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnquitaralistador.setText("Quitar");
        btnquitaralistador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitaralistadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnalistador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnquitaralistador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnalistador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnquitaralistador)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Lista Armadores");

        jScrollPane5.setViewportView(jarmador);

        btnarmador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnarmador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarmadorActionPerformed(evt);
            }
        });

        btnquitararmador.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnquitararmador.setText("Quitar");
        btnquitararmador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitararmadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnquitararmador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnarmador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnarmador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnquitararmador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Lista Perfiladores");

        jScrollPane2.setViewportView(jperfilador);

        btnperfilador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnperfilador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperfiladorActionPerformed(evt);
            }
        });

        btnquitarperfilador.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnquitarperfilador.setText("Quitar");
        btnquitarperfilador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarperfiladorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnquitarperfilador, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnperfilador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnperfilador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnquitarperfilador)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Lista cortadores");

        jScrollPane3.setViewportView(jcortador);

        btnvercortador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnvercortador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvercortadorActionPerformed(evt);
            }
        });

        btnquitarcortador.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnquitarcortador.setText("Quitar");
        btnquitarcortador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarcortadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnvercortador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnquitarcortador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvercortador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnquitarcortador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnregistrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnverpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverpedidoActionPerformed
   IFROrden.verificar=2;
   IFRBuscarPedido buscarPedido = new IFRBuscarPedido();
   buscarPedido.setTitle("Pedidos");
   desktopPane.add(buscarPedido);
   
   int x = (desktopPane.getWidth() / 2) - (buscarPedido.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarPedido.getHeight() / 2);
   buscarPedido.setLocation(x, y);
   
   buscarPedido.setVisible(true);
   
    }//GEN-LAST:event_btnverpedidoActionPerformed

    public static boolean  existeEnLista( DefaultListModel modeloLista, String dato){
    boolean  confirmar=false;
     for(int i=0; i<modeloLista.getSize();i++){
     if (modeloLista.getElementAt(i).equals(dato)){
        confirmar=true;
     }   
     }
    return confirmar;
    }
    
    public static void agregarDatosLista(DefaultListModel modeloLista, String dato, JList jlista,String nombre){
        if(!existeEnLista(modeloLista, dato)){
        modeloLista.addElement(dato);
        jlista.setModel(modeloLista);
        }else{
        JOptionPane.showMessageDialog(null,"Ya existe "+nombre+" en la lista");
        }
    
    
    }
    
    
    
    public void limpiarTabla(){
    modelo2.getDataVector().removeAllElements();
    tabla.updateUI();
    stockInsumo.clear();
    txtidpedido.setText("");
    }
    
 
    
    
    
    
    private void btnverinsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverinsumoActionPerformed
   IFRBuscarInsumo buscarInsumo = new IFRBuscarInsumo ();
   //buscarPedido.setTitle("Pedidos");
   desktopPane.add(buscarInsumo);
   
   int x = (desktopPane.getWidth() / 2) - (buscarInsumo.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarInsumo.getHeight() / 2);
   buscarInsumo.setLocation(x, y);
   
   buscarInsumo.setVisible(true);
    }//GEN-LAST:event_btnverinsumoActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        //establecer el registro
        
        OrdenProduccion ordenProduccion = new OrdenProduccion();
        ordenProduccion.setFecha(new Timestamp(System.currentTimeMillis()));
        
    if(validarCampos()){
        int pedidoid=Integer.parseInt(txtidpedido.getText());
        Pedido pedido = new Pedido();
    
     if(validarStock()){ 
        if(ordenProduccion.registrarProduccion(pedidoid)){
            int idProduccion=datos.ClienteService.ultimoRegistro("id_produccion","produccion");  //captamos el id de la produccion
            //añadimos los insumos a la tabla datalle de insumos
            for(int i=0;i<modelo2.getRowCount();i++){
               datos.ClienteService.registrarDetalleInsumo(Integer.parseInt(modelo2.getValueAt(i, 2).toString()),idProduccion,Integer.parseInt(modelo2.getValueAt(i, 0).toString()));  
            }
            
            for(int i=0; i<modeloListaCortador.getSize();i++){
            datos.ClienteService.registrarDetalleTrabajador(Integer.parseInt(modeloListaCortador.getElementAt(i).toString()),idProduccion);
            }
            
            for(int i=0; i<modeloListaArmador.getSize();i++){
            datos.ClienteService.registrarDetalleTrabajador(Integer.parseInt(modeloListaArmador.getElementAt(i).toString()),idProduccion);
            }
             
            for(int i=0; i<modeloListaPerfilador.getSize();i++){
            datos.ClienteService.registrarDetalleTrabajador(Integer.parseInt(modeloListaPerfilador.getElementAt(i).toString()),idProduccion);
            }
            
            for(int i=0; i<modeloListaAlistador.getSize();i++){
            datos.ClienteService.registrarDetalleTrabajador(Integer.parseInt(modeloListaAlistador.getElementAt(i).toString()),idProduccion);
            }
        
            pedido.setEstado("EN PRODUCCION");
            pedido.actualizarEstadoPedido(pedidoid);
            
       modeloListaAlistador= new DefaultListModel();
       modeloListaCortador= new DefaultListModel();
       modeloListaPerfilador= new DefaultListModel();
       modeloListaArmador= new DefaultListModel();
       
      limpiarLista(modeloListaAlistador, jalistador);
      limpiarLista(modeloListaCortador, jcortador);
      limpiarLista(modeloListaPerfilador, jperfilador);
      limpiarLista(modeloListaArmador, jarmador);
             limpiarTabla();
            
        }
        
       } 
     
     //
    }
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnvercortadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvercortadorActionPerformed
   verificar=1;
   IFRBuscarTrabajador buscarTrabajador = new IFRBuscarTrabajador ();
   buscarTrabajador.setTitle("Cortador");
   
   desktopPane.add(buscarTrabajador);
  
   int x = (desktopPane.getWidth() / 2) - (buscarTrabajador.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarTrabajador.getHeight() / 2);
   buscarTrabajador.setLocation(x, y);
   
   buscarTrabajador.setVisible(true);
    
    }//GEN-LAST:event_btnvercortadorActionPerformed

    
    
    
    
    private void btnperfiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperfiladorActionPerformed
   
        verificar=2;
        IFRBuscarTrabajador buscarTrabajador = new IFRBuscarTrabajador ();
   //buscarPedido.setTitle("Pedidos");
   
   desktopPane.add(buscarTrabajador);
   buscarTrabajador.setTitle("Perfilador");
   
   int x = (desktopPane.getWidth() / 2) - (buscarTrabajador.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarTrabajador.getHeight() / 2);
   buscarTrabajador.setLocation(x, y);
   
   buscarTrabajador.setVisible(true);
    }//GEN-LAST:event_btnperfiladorActionPerformed

    
  
    
     
     
     public DefaultListModel  limpiarLista(DefaultListModel modelo, JList lista ){
     modelo= new  DefaultListModel();
     lista.setModel(modelo);
     return modelo;
    }
     
   
    
   
    
    
    private void btnarmadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarmadorActionPerformed
         
        verificar=3;
        IFRBuscarTrabajador buscarTrabajador = new IFRBuscarTrabajador ();
   
   desktopPane.add(buscarTrabajador);
   buscarTrabajador.setTitle("Armador");
   
   int x = (desktopPane.getWidth() / 2) - (buscarTrabajador.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarTrabajador.getHeight() / 2);
   buscarTrabajador.setLocation(x, y);
   
   buscarTrabajador.setVisible(true);
    }//GEN-LAST:event_btnarmadorActionPerformed

    private void btnalistadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalistadorActionPerformed
        verificar=4; 
        IFRBuscarTrabajador buscarTrabajador = new IFRBuscarTrabajador ();
   //buscarPedido.setTitle("Pedidos");
   desktopPane.add(buscarTrabajador);
   
   buscarTrabajador.setTitle("Alistador");
   int x = (desktopPane.getWidth() / 2) - (buscarTrabajador.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarTrabajador.getHeight() / 2);
   buscarTrabajador.setLocation(x, y);
   
   buscarTrabajador.setVisible(true);
    }//GEN-LAST:event_btnalistadorActionPerformed

    private void btneliminarfilatablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarfilatablaActionPerformed
    
        if (tabla.getSelectedRow()>=0){
            int idSeleccionado=Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(),0).toString());
            stockInsumo.remove(tabla.getSelectedRow());
            modelo2.removeRow(tabla.getSelectedRow());
            
          
        }else {
        JOptionPane.showMessageDialog(null,"Ninguna fila seleccionada");
        
        }
  
    }//GEN-LAST:event_btneliminarfilatablaActionPerformed

    
    
    public void quitarPerfilador(DefaultListModel modeloLista, JList lista){
        modeloLista.remove(lista.getSelectedIndex());
    }
    
    
    
    
    private void btnquitarperfiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarperfiladorActionPerformed
        int fila = jperfilador.getSelectedIndex();
        if (fila>=0){
         quitarPerfilador(modeloListaPerfilador, jperfilador);
        }else {
         JOptionPane.showMessageDialog(null,"Ningun perfilador seleccionado");
        }
    }//GEN-LAST:event_btnquitarperfiladorActionPerformed

    private void btnquitarcortadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarcortadorActionPerformed
       
       
         int fila = jcortador.getSelectedIndex();
        if (fila>=0){
         quitarPerfilador(modeloListaCortador, jcortador);
        }else {
         JOptionPane.showMessageDialog(null,"Ningun cortador seleccionado");
        }
       
       
       
    }//GEN-LAST:event_btnquitarcortadorActionPerformed

    private void btnquitararmadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitararmadorActionPerformed
        
        int fila = jarmador.getSelectedIndex();
        if (fila>=0){
        quitarPerfilador(modeloListaArmador, jarmador);
        }else {
         JOptionPane.showMessageDialog(null,"Ningun armador seleccionado");
        }
        
    }//GEN-LAST:event_btnquitararmadorActionPerformed

    private void btnquitaralistadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitaralistadorActionPerformed
        
         int fila = jalistador.getSelectedIndex();
        if (fila>=0){
        quitarPerfilador(modeloListaAlistador, jalistador);
        }else {
         JOptionPane.showMessageDialog(null,"Ningun alistador seleccionado");
        }
    }//GEN-LAST:event_btnquitaralistadorActionPerformed


    
    //validamos el stock
    
    
    private boolean  validarCampos(){
        boolean confirmar=true;
      if (txtidpedido.getText().trim().equals("") ){
        confirmar=false;
        JOptionPane.showMessageDialog(null,"Escoger pedido");
        }else if( tabla.getRowCount() == 0) {
            confirmar=false;
             JOptionPane.showMessageDialog(null,"Escoger insumos");
            }else if ( jcortador.getModel().getSize()==0){
                   confirmar=false;
                    JOptionPane.showMessageDialog(null,"No hay ningun cortador");
                   }else if( jarmador.getModel().getSize()==0 ){
                            confirmar=false;
                             JOptionPane.showMessageDialog(null,"No hay ningun armador");
                            }else if (jperfilador.getModel().getSize()==0 ){
                                    confirmar=false;
                                     JOptionPane.showMessageDialog(null,"No hay ningun perfilador");
                                    } else if( jalistador.getModel().getSize()==0   ){
                                                confirmar=false;
                                                 JOptionPane.showMessageDialog(null,"No hay ningun alistador");
                                            }
        
                                        
        
        return confirmar;
    
    
    }
    
    private void actualizarStockInsumo(){
       Insumo insumo = new Insumo();
       int resto=0;
       for(int i=0; i<stockInsumo.size();i++){
       int idInsumo=Integer.parseInt(modelo2.getValueAt(i, 0).toString());
       resto = Integer.parseInt(stockInsumo.get(i).toString()) - Integer.parseInt(modelo2.getValueAt(i, 2).toString());
       insumo.setCantidad(resto);
       insumo.actualizarStock(idInsumo);
       }
     
    }
    
    //validar stock -comprobar 
    private boolean validarStock(){
    boolean confirmar=false;
    int contador=0;
      for(int i=0; i<stockInsumo.size(); i++){
         if(modelo2.getValueAt(i, 2)==null){ 
             JOptionPane.showMessageDialog(null,"El insumo "+modelo2.getValueAt(i, 1).toString()+" No tiene tiene cantidad señalada");
         }else {
             
          if(Integer.parseInt(modelo2.getValueAt(i, 2).toString())<=stockInsumo.get(i)){
              contador++;
          }else{
           JOptionPane.showMessageDialog(null,"El insumo "+modelo2.getValueAt(i, 1).toString()+" No tiene stock suficiente");
          }

         }
         
         
         
       }
    
    if (contador==stockInsumo.size()){
       confirmar=true;
       actualizarStockInsumo();
    }
    
    return confirmar;
    }

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalistador;
    private javax.swing.JButton btnarmador;
    private javax.swing.JButton btneliminarfilatabla;
    private javax.swing.JButton btnperfilador;
    private javax.swing.JButton btnquitaralistador;
    private javax.swing.JButton btnquitararmador;
    private javax.swing.JButton btnquitarcortador;
    private javax.swing.JButton btnquitarperfilador;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvercortador;
    private javax.swing.JButton btnverinsumo;
    private javax.swing.JButton btnverpedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JList<String> jalistador;
    public static javax.swing.JList<String> jarmador;
    public static javax.swing.JList<String> jcortador;
    public static javax.swing.JList<String> jperfilador;
    public static javax.swing.JTable tabla;
    public static javax.swing.JTextField txtidpedido;
    // End of variables declaration//GEN-END:variables
}
