/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import datos.ClienteService;
import static datos.ClienteService.buscarPedido;
import static interfaces.IFRPedido.txtcliente;
import static interfaces.IUPrincipal.desktopPane;
import java.awt.Color;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetallePedido;
import modelo.Pedido;

/**
 *
 * @author Michaell
 */
public class IFRPedido2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFRPedido2
     */
    public static DefaultTableModel modelo2;
    public IFRPedido2() {
        initComponents();
       
       modelo2= new DefaultTableModel();
       modelo2.addColumn("id modelo");
       modelo2.addColumn("Nombre Modelo");
       modelo2.addColumn("Cantidad(docenas)");
       modelo2.addColumn("Color");
       modelo2.addColumn("Nro taco");
       modelo2.addColumn("Talla");
       
       tabla.setModel(modelo2);
       tabla.getTableHeader().setReorderingAllowed(false) ;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnvermodelos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnquitar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnvercliente = new javax.swing.JButton();
        txtidcliente = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pedidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                switch (colIndex) {
                    case 0:
                    return false;
                    case 1:
                    return false;
                    default:
                    return true;
                }
            }
        };
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnvermodelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnvermodelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvermodelosActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoger Modelo");

        btnquitar.setText("Quitar");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 558, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnvermodelos)
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnquitar)
                .addGap(320, 320, 320))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvermodelos)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnquitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Escoger cliente");

        btnvercliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Buscar.gif"))); // NOI18N
        btnvercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverclienteActionPerformed(evt);
            }
        });

        txtidcliente.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnvercliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnvercliente)
                    .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Guardar.gif"))); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnregistrar)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnverclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverclienteActionPerformed
   IFRBuscarCliente buscarcliente = new IFRBuscarCliente();
    buscarcliente.setTitle("Busca Cliente");
   desktopPane.add(buscarcliente);
   
   int x = (desktopPane.getWidth() / 2) - (buscarcliente.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarcliente.getHeight() / 2);
   buscarcliente.setLocation(x, y);
   
   buscarcliente.setVisible(true);
    }//GEN-LAST:event_btnverclienteActionPerformed

    private void btnvermodelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvermodelosActionPerformed
   IFRBuscarModelo buscarModelo = new IFRBuscarModelo();
   desktopPane.add(buscarModelo);
   
   int x = (desktopPane.getWidth() / 2) - (buscarModelo.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (buscarModelo.getHeight() / 2);
   buscarModelo.setLocation(x, y);
   
   buscarModelo.setVisible(true);
    }//GEN-LAST:event_btnvermodelosActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        Pedido pedido = new Pedido();
        DetallePedido detallepedido= new DetallePedido();
        
        pedido.setEstado("Sin produccion");
        pedido.setFecha(new Timestamp(System.currentTimeMillis()));
        //int idcliente=Integer.parseInt(txtidcliente.getText());
        
       if(validar()){ 
           int idcliente=Integer.parseInt(txtidcliente.getText());
        if (pedido.registrarPedido(idcliente)){
            int idPedido=datos.ClienteService.ultimoRegistro("id_pedido","pedido");
            
              for(int i=0;i<modelo2.getRowCount();i++){
                    detallepedido.setCantidadEnDocenas(Integer.parseInt(modelo2.getValueAt(i, 2).toString()));
                    detallepedido.setColor(modelo2.getValueAt(i, 3).toString());
                    detallepedido.setNroTaco(Integer.parseInt(modelo2.getValueAt(i, 4).toString()));
                    detallepedido.setTalla(Integer.parseInt(modelo2.getValueAt(i, 5).toString()));
                    detallepedido.registrarDetallePedido(idPedido,Integer.parseInt(modelo2.getValueAt(i, 0).toString()));
              
            }
        
         limpiarTabla();
        }
        
       }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
         if (tabla.getSelectedRow()>=0){
            int idSeleccionado=Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(),0).toString());
            modelo2.removeRow(tabla.getSelectedRow());
            
          
        }else {
        JOptionPane.showMessageDialog(null,"Ninguna fila seleccionada");
        
        }
        
        
        
    }//GEN-LAST:event_btnquitarActionPerformed

    public void limpiarTabla(){
    modelo2.getDataVector().removeAllElements();
    tabla.updateUI();
    txtidcliente.setText("");
    }
    
    
    
  
   
   
  

   
   public boolean validar(){
   boolean verificar=true;
   if(txtidcliente.getText().trim().equals("")){
       verificar=false;
   JOptionPane.showMessageDialog(null,"Colocar cliente para alistar pedido");
   }else if(tabla.getRowCount() == 0){
        verificar=false;
   JOptionPane.showMessageDialog(null,"Seleccionar un modelo");
   }else {
   if (!validarColumnas()){
        verificar=false;
   }
   
   }
   

   return verificar;
   }
   
   public boolean validarColumnas(){
   boolean verificar=true;
   for (int i=0; i<tabla.getRowCount();i++){
            if (modelo2.getValueAt(i, 2)==null){
                verificar=false;
                i=tabla.getRowCount();
                JOptionPane.showMessageDialog(null,"Seleccionar cantidad");
            }

            if (modelo2.getValueAt(i, 3)==null){
                verificar=false;
                i=tabla.getRowCount();
                JOptionPane.showMessageDialog(null,"Seleccionar color");
              }
   
            if (modelo2.getValueAt(i, 4)==null){
                verificar=false;
                i=tabla.getRowCount();
                JOptionPane.showMessageDialog(null,"Seleccionar nro de taco");
            }
   
            if (modelo2.getValueAt(i, 5)==null){
                verificar=false;
                i=tabla.getRowCount();
                JOptionPane.showMessageDialog(null,"Seleccionar talla");
            }
   
   
   
   
   }
   
   return verificar;
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnquitar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvercliente;
    private javax.swing.JButton btnvermodelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla;
    public static javax.swing.JTextField txtidcliente;
    // End of variables declaration//GEN-END:variables
}
