/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import datos.ClienteService;
import static interfaces.IFRReporteCliente.crearConexion;
import static interfaces.IFRReporteCliente.impirmirReporte;
import static interfaces.IUPrincipal.desktopPane;
import java.security.Principal;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Michaell
 */
public class IFRReportePedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFRReportePedidos
     */
    
         String estado;
     
    private static EntityManagerFactory emf=Persistence.createEntityManagerFactory("Dapp202020PU");
    private static EntityManager em;
    HashMap parametros;
    Connection conn;
    public IFRReportePedidos() {
        initComponents();
        estado="";
        mostrarPedidos();
         tabla.getTableHeader().setReorderingAllowed(false) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnreportepedidos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Reporte de pedidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                switch (colIndex) {
                    case 0:
                    return false;
                    case 1:
                    return false;
                    case 2:
                    return false;
                    case 3:
                    return false;
                    default:
                    return false;
                }
            }
        };
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setFocusable(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnreportepedidos.setText("Report");
        btnreportepedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportepedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(btnreportepedidos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreportepedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreportepedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportepedidosActionPerformed
          int fila=tabla.getRowCount();
   if (fila>0){
        parametros= new HashMap();
        try {
            crearConexion();
            em.getTransaction().begin();
            parametros.put("ESTADO", estado);
            conn=em.unwrap(java.sql.Connection.class);
            impirmirReporte("ReportePedidos.jasper",parametros,conn);
            em.getTransaction().commit();
            
        } catch (Exception ex) {
            
             Logger.getLogger(IUPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }else {
        JOptionPane.showMessageDialog(null,"No hay datos");
   
   }
    }//GEN-LAST:event_btnreportepedidosActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
    IFRReporteDetallePedido rdetallepedido = new IFRReporteDetallePedido();
    //rdetallepedido.setTitle("Busca Cliente");
   desktopPane.add(rdetallepedido);
   int x = (desktopPane.getWidth() / 2) - (rdetallepedido.getWidth() / 2);
   int y = (desktopPane.getHeight() / 2) - (rdetallepedido.getHeight() / 2);
   rdetallepedido.setLocation(x, y);
   rdetallepedido.setVisible(true);
   
            int fila=tabla.getSelectedRow();
            if(fila>=0){
                interfaces.IFRReporteDetallePedido.txtidpedido.setText(String.valueOf(tabla.getValueAt(fila, 0)));
                interfaces.IFRReporteDetallePedido.txtfechapedido.setText(String.valueOf(tabla.getValueAt(fila, 1)));
                 interfaces.IFRReporteDetallePedido.txtestadopedido.setText(String.valueOf(tabla.getValueAt(fila, 2)));
                 interfaces.IFRReporteDetallePedido.mostrarDetallePedido(String.valueOf(tabla.getValueAt(fila, 0)));
                //dispose();
              
            }
   
    }//GEN-LAST:event_tablaMouseClicked
    public static EntityManager crearConexion(){
        return em=emf.createEntityManager();
       }  
          
        
        public static void impirmirReporte(String reporte, Map parametros, Connection conn){
            try {
                JasperReport jr= (JasperReport)JRLoader.loadObject(Principal.class.getResource("/reportes/" + reporte));
                JasperPrint jp = JasperFillManager.fillReport(jr, parametros, conn);
                
                
                JasperViewer jv= new JasperViewer(jp, false);
                jv.setVisible(true);
            } catch (JRException ex ) {
                Logger.getLogger(IUPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }

           public void mostrarPedidos() {
        DefaultTableModel modelo = ClienteService. mostrarPedidosConEstado(estado);
        tabla.setModel(modelo);
    }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreportepedidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
