/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import datos.ClienteService;
import java.security.Principal;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Michaell
 */
public class IFRReporteCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFRReporteCliente
     */
     ButtonGroup gupoRadioButton;
     String estado;
     
    private static EntityManagerFactory emf=Persistence.createEntityManagerFactory("Dapp202020PU");
    private static EntityManager em;
    HashMap parametros;
    Connection conn;
    public IFRReporteCliente() {
        initComponents();
        estado="Sin produccion";
         mostrarClientes();
        gupoRadioButton= new  ButtonGroup();
        gupoRadioButton.add(rsinproduccion);
        gupoRadioButton.add(rproduccion);
        gupoRadioButton.add(rterminado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        rproduccion = new javax.swing.JRadioButton();
        rsinproduccion = new javax.swing.JRadioButton();
        rterminado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnreporte = new javax.swing.JButton();

        setClosable(true);
        setTitle("Reporte Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        rproduccion.setText("En produccion");
        rproduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rproduccionMouseClicked(evt);
            }
        });
        rproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rproduccionActionPerformed(evt);
            }
        });

        rsinproduccion.setSelected(true);
        rsinproduccion.setText("Sin produccion");
        rsinproduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rsinproduccionMouseClicked(evt);
            }
        });
        rsinproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsinproduccionActionPerformed(evt);
            }
        });

        rterminado.setText("Terminado");
        rterminado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rterminadoMouseClicked(evt);
            }
        });
        rterminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rterminadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pedidos :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rproduccion)
                .addGap(18, 18, 18)
                .addComponent(rsinproduccion)
                .addGap(18, 18, 18)
                .addComponent(rterminado)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rproduccion)
                    .addComponent(rsinproduccion)
                    .addComponent(rterminado)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnreporte.setText("Report");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(btnreporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rproduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rproduccionMouseClicked

    }//GEN-LAST:event_rproduccionMouseClicked

    private void rproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rproduccionActionPerformed
       if (rproduccion.isSelected()==true){
      estado="EN PRODUCCION";
      mostrarClientes();
        
   }
    }//GEN-LAST:event_rproduccionActionPerformed

    private void rsinproduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsinproduccionMouseClicked

    }//GEN-LAST:event_rsinproduccionMouseClicked

    private void rsinproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsinproduccionActionPerformed
   if (rsinproduccion.isSelected()==true){
       estado="Sin produccion";
     mostrarClientes();
        
   }
    }//GEN-LAST:event_rsinproduccionActionPerformed

    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
   int fila=tabla.getRowCount();
   if (fila>0){
        parametros= new HashMap();
        try {
            crearConexion();
            em.getTransaction().begin();
            parametros.put("ESTADO", estado);
            conn=em.unwrap(java.sql.Connection.class);
            impirmirReporte("ReporteClientes.jasper",parametros,conn);
            em.getTransaction().commit();
            
        } catch (Exception ex) {
            
             Logger.getLogger(IUPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }else {
        JOptionPane.showMessageDialog(null,"No hay datos");
   
   }
    }//GEN-LAST:event_btnreporteActionPerformed

       public static EntityManager crearConexion(){
        return em=emf.createEntityManager();
       }  
          
        
        public static void impirmirReporte(String reporte, Map parametros, Connection conn){
            try {
                JasperReport jr= (JasperReport)JRLoader.loadObject(Principal.class.getResource("/reportes/" + reporte));
                JasperPrint jp = JasperFillManager.fillReport(jr, parametros, conn);
                
                
                JasperViewer jv= new JasperViewer(jp, false);
                jv.setVisible(true);
            } catch (JRException ex ) {
                Logger.getLogger(IUPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    
    
    
    private void rterminadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rterminadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rterminadoMouseClicked

    private void rterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rterminadoActionPerformed
      if (rterminado.isSelected()==true){
      estado="TERMINADO";
      mostrarClientes();
        
   }
    }//GEN-LAST:event_rterminadoActionPerformed


    public void mostrarClientes() {
        DefaultTableModel modelo = ClienteService.mostrarClientesSegunEstado(estado);
        tabla.setModel(modelo);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rproduccion;
    private javax.swing.JRadioButton rsinproduccion;
    private javax.swing.JRadioButton rterminado;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
