/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JInternalFrame;

/**
 *
 * @author JACS
 */
public class IUPrincipal extends javax.swing.JFrame {

    private IFAbout about;
    private IFRClientes clientes;
    private IFRTrabajadores trabajadores;
    private IFRModelo modelo;
    private IFRProveedor proveedor;
    private IFRInsumos insumos;
    private IFRListaPedidos listaPedidos;
    private IFRProduccion produccion;
    private IFRPedido2 pedido;
    private IFRReporteCliente rcliente;
    private IFRReportePedidos rpedidos;
    private IFRReporteInsumos rinsumos;
    private IFRReporteTrabajadores rtrabajador;
    
     
    

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mnuItemRegistroClientes = new javax.swing.JMenuItem();
        mnuItemRegistroTrabajadores = new javax.swing.JMenuItem();
        mnuItemRegistroModelo = new javax.swing.JMenuItem();
        mnuItemRegistroProveedor = new javax.swing.JMenuItem();
        mnuItemRegistroInsumos = new javax.swing.JMenuItem();
        mnuOrdenes = new javax.swing.JMenu();
        mnuItemOrdenesPedido = new javax.swing.JMenuItem();
        mnuItemOrdenesOrden = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuItemAsignarRecursos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemReporteCliente = new javax.swing.JMenuItem();
        itemReportePedidos = new javax.swing.JMenuItem();
        itemReporteInsumos = new javax.swing.JMenuItem();
        itemReporteTrabajador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuClientes.setMnemonic('e');
        mnuClientes.setText("Mantenimiento");

        mnuItemRegistroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icono cliente.png"))); // NOI18N
        mnuItemRegistroClientes.setMnemonic('t');
        mnuItemRegistroClientes.setText("Cliente");
        mnuItemRegistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manejadorClientes(evt);
            }
        });
        mnuClientes.add(mnuItemRegistroClientes);

        mnuItemRegistroTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trabaa.png"))); // NOI18N
        mnuItemRegistroTrabajadores.setText("Trabajador");
        mnuItemRegistroTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistroTrabajadoresActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuItemRegistroTrabajadores);

        mnuItemRegistroModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mdd.png"))); // NOI18N
        mnuItemRegistroModelo.setText("Modelos");
        mnuItemRegistroModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistroModeloActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuItemRegistroModelo);

        mnuItemRegistroProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/provv.png"))); // NOI18N
        mnuItemRegistroProveedor.setText("Proveedor");
        mnuItemRegistroProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistroProveedorActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuItemRegistroProveedor);

        mnuItemRegistroInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/inss.png"))); // NOI18N
        mnuItemRegistroInsumos.setText("Insumos");
        mnuItemRegistroInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistroInsumosActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuItemRegistroInsumos);

        menuBar.add(mnuClientes);

        mnuOrdenes.setText("Pedidos");
        mnuOrdenes.setToolTipText("");

        mnuItemOrdenesPedido.setText("Pedido");
        mnuItemOrdenesPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemOrdenesPedidoActionPerformed(evt);
            }
        });
        mnuOrdenes.add(mnuItemOrdenesPedido);

        mnuItemOrdenesOrden.setText("ver lista de pedidos");
        mnuItemOrdenesOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemOrdenesOrdenActionPerformed(evt);
            }
        });
        mnuOrdenes.add(mnuItemOrdenesOrden);

        menuBar.add(mnuOrdenes);

        jMenu1.setText("Produccion");

        mnuItemAsignarRecursos.setText("Alistar Produccion");
        mnuItemAsignarRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAsignarRecursosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemAsignarRecursos);

        menuBar.add(jMenu1);

        jMenu2.setText("Reportes");

        itemReporteCliente.setText("Clientes");
        itemReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteClienteActionPerformed(evt);
            }
        });
        jMenu2.add(itemReporteCliente);

        itemReportePedidos.setText("Pedidos");
        itemReportePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportePedidosActionPerformed(evt);
            }
        });
        jMenu2.add(itemReportePedidos);

        itemReporteInsumos.setText("Insumos");
        itemReporteInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteInsumosActionPerformed(evt);
            }
        });
        jMenu2.add(itemReporteInsumos);

        itemReporteTrabajador.setText("Trabajadores");
        itemReporteTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteTrabajadorActionPerformed(evt);
            }
        });
        jMenu2.add(itemReporteTrabajador);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        desktopPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manejadorClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manejadorClientes
        if(evt.getSource()==mnuItemRegistroClientes){
            if(clientes!=null){
                desktopPane.remove(clientes);
            }
            clientes=new IFRClientes();
            desktopPane.add(clientes);
            centrarVentana(clientes);
            clientes.setVisible(true);
        }
    }//GEN-LAST:event_manejadorClientes

    private void mnuItemRegistroTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistroTrabajadoresActionPerformed
               if(evt.getSource()==mnuItemRegistroTrabajadores){
            if(trabajadores!=null){
                desktopPane.remove(trabajadores);
            }
            trabajadores=new IFRTrabajadores();
            desktopPane.add(trabajadores);
            centrarVentana(trabajadores);
            trabajadores.setVisible(true);
        }
    }//GEN-LAST:event_mnuItemRegistroTrabajadoresActionPerformed

    private void mnuItemRegistroModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistroModeloActionPerformed
           if(evt.getSource()==mnuItemRegistroModelo){
            if(modelo!=null){
                desktopPane.remove(modelo);
            }
            modelo=new IFRModelo();
            desktopPane.add(modelo);
            centrarVentana(modelo);
            modelo.setVisible(true);
        }
    }//GEN-LAST:event_mnuItemRegistroModeloActionPerformed

    private void mnuItemRegistroProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistroProveedorActionPerformed
              if(evt.getSource()==mnuItemRegistroProveedor){
            if(proveedor!=null){
                desktopPane.remove(proveedor);
            }
            proveedor=new IFRProveedor();
            desktopPane.add(proveedor);
            centrarVentana(proveedor);
           proveedor.setVisible(true);
        }
    }//GEN-LAST:event_mnuItemRegistroProveedorActionPerformed

    private void mnuItemRegistroInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistroInsumosActionPerformed
         if(evt.getSource()==mnuItemRegistroInsumos){
            if(insumos!=null){
                desktopPane.remove(insumos);
            }
            insumos=new IFRInsumos();
            desktopPane.add(insumos);
            centrarVentana(insumos);
           insumos.setVisible(true);
        }
    }//GEN-LAST:event_mnuItemRegistroInsumosActionPerformed

    private void mnuItemOrdenesPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemOrdenesPedidoActionPerformed
        // mnuItemOrdenesPedido
            if(evt.getSource()==mnuItemOrdenesPedido){
            if(pedido!=null){
                desktopPane.remove(pedido);
            }
            pedido=new IFRPedido2();
            desktopPane.add(pedido);
            centrarVentana(pedido);
           pedido.setVisible(true);
        }
        
        
        
        
    }//GEN-LAST:event_mnuItemOrdenesPedidoActionPerformed

    private void mnuItemOrdenesOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemOrdenesOrdenActionPerformed
        // mnuItemOrdenesOrden
                if(evt.getSource()==mnuItemOrdenesOrden){
            if(listaPedidos!=null){
                desktopPane.remove(listaPedidos);
            }
            listaPedidos=new IFRListaPedidos();
            desktopPane.add(listaPedidos);
            centrarVentana(listaPedidos);
           listaPedidos.setVisible(true);
        }
        
        
    }//GEN-LAST:event_mnuItemOrdenesOrdenActionPerformed

    private void mnuItemAsignarRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAsignarRecursosActionPerformed
            if(evt.getSource()==mnuItemAsignarRecursos){
            if(produccion!=null){
                desktopPane.remove(produccion);
            }
            produccion=new IFRProduccion();
            desktopPane.add(produccion);
            centrarVentana(produccion);
           produccion.setVisible(true);
        }
    }//GEN-LAST:event_mnuItemAsignarRecursosActionPerformed

    private void itemReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteClienteActionPerformed
         if(evt.getSource()==itemReporteCliente){
            if(rcliente!=null){
                desktopPane.remove(rcliente);
            }
            rcliente =new IFRReporteCliente();
            desktopPane.add(rcliente);
            centrarVentana(rcliente);
           rcliente.setVisible(true);
        }
    }//GEN-LAST:event_itemReporteClienteActionPerformed

    private void itemReportePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportePedidosActionPerformed
        if(evt.getSource()==itemReportePedidos){
            if(rpedidos!=null){
                desktopPane.remove(rpedidos);
            }
            rpedidos =new IFRReportePedidos();
            desktopPane.add(rpedidos);
            centrarVentana(rpedidos);
           rpedidos.setVisible(true);
        }
    }//GEN-LAST:event_itemReportePedidosActionPerformed

    private void itemReporteInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteInsumosActionPerformed
            if(evt.getSource()==itemReporteInsumos){
            if(rinsumos!=null){
                desktopPane.remove(rpedidos);
            }
            rinsumos =new IFRReporteInsumos();
            desktopPane.add(rinsumos);
            centrarVentana(rinsumos);
           rinsumos.setVisible(true);
        }
    }//GEN-LAST:event_itemReporteInsumosActionPerformed

    private void itemReporteTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteTrabajadorActionPerformed
               if(evt.getSource()==itemReporteTrabajador){
            if(rtrabajador!=null){
                desktopPane.remove(rtrabajador);
            }
            rtrabajador =new IFRReporteTrabajadores();
            desktopPane.add(rtrabajador);
            centrarVentana(rtrabajador);
           rtrabajador.setVisible(true);
        }
    }//GEN-LAST:event_itemReporteTrabajadorActionPerformed
    
    private void centrarVentana(JInternalFrame ventana){
        
        int x = (desktopPane.getWidth() / 2) - (ventana.getWidth() / 2);
        int y = (desktopPane.getHeight() / 2) - (ventana.getHeight() / 2);
        ventana.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemReporteCliente;
    private javax.swing.JMenuItem itemReporteInsumos;
    private javax.swing.JMenuItem itemReportePedidos;
    private javax.swing.JMenuItem itemReporteTrabajador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuItemAsignarRecursos;
    private javax.swing.JMenuItem mnuItemOrdenesOrden;
    private javax.swing.JMenuItem mnuItemOrdenesPedido;
    private javax.swing.JMenuItem mnuItemRegistroClientes;
    private javax.swing.JMenuItem mnuItemRegistroInsumos;
    private javax.swing.JMenuItem mnuItemRegistroModelo;
    private javax.swing.JMenuItem mnuItemRegistroProveedor;
    private javax.swing.JMenuItem mnuItemRegistroTrabajadores;
    private javax.swing.JMenu mnuOrdenes;
    // End of variables declaration//GEN-END:variables

}
